###
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "This is product 1",
    "price": 10.99,
    "imageUrl": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "quantity": 100
}

###
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "name": "Product 2",
    "description": "This is product 3",
    "price": 102.99,
    "imageUrl": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "quantity": 202
}

###
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "name": "Product 3",
    "description": "This is product 3",
    "price": 30.99,
    "imageUrl": "",
    "quantity": 3
}

###
GET http://localhost:8080/api/products

###
GET http://localhost:8080/api/products/5

###
POST http://localhost:8080/api/products/6
Content-Type: application/json

{
    "name": "Product Edit 1",
    "description": "This is product Edit 3",
    "price": 30.99,
    "imageUrl": "",
    "quantity": 3
}

###
DELETE  http://localhost:8080/api/products/6